using HostelPro.Models;

namespace HostelPro.Services;

public interface IHostelRepository
{
    Task<HostelSetting> GetSettingsAsync();
    Task<DashboardStats> GetDashboardStatsAsync();
    Task<List<Room>> GetPublicRoomsAsync();
    Task<List<Room>> GetRoomsAsync();
    Task SaveRoomAsync(RoomForm form, string actor);
    Task DeleteRoomAsync(Guid roomId, string actor);
    Task<List<Bed>> GetBedsAsync();
    Task SaveBedAsync(BedForm form, string actor);
    Task DeleteBedAsync(Guid bedId, string actor);
    Task<List<Tenant>> GetTenantsAsync();
    Task SaveTenantAsync(TenantForm form, string actor);
    Task StartTenantNoticeAsync(TenantNoticeForm form, string actor);
    Task<decimal> VacateTenantAsync(TenantVacateForm form, string actor);
    Task<List<TenantApplication>> GetTenantApplicationsAsync();
    Task<TenantApplication> SubmitTenantApplicationAsync(TenantApplicationForm form);
    Task<Tenant> ApproveTenantApplicationAsync(TenantApplicationApprovalForm form, string actor);
    Task UpdateTenantApplicationStatusAsync(Guid applicationId, string status, string actor);
    Task<List<Bill>> GetBillsAsync();
    Task SaveBillAsync(BillForm form, string actor);
    Task<int> AutoGenerateBillsAsync(string actor);
    Task MarkInvoiceSentAsync(Guid billId, string actor);
    Task<List<Payment>> GetPaymentsAsync();
    Task<Payment> RecordPaymentAsync(PaymentForm form, string actor);
    Task<List<PaymentLink>> GetPaymentLinksAsync();
    Task<CreatedPaymentLink> CreatePaymentLinkAsync(Guid billId, string actor);
    Task<PaymentLink?> GetPaymentLinkByTokenAsync(string token);
    Task<PaymentAttempt> SubmitPaymentAttemptAsync(string token, PublicPaymentAttemptForm form);
    Task<List<PaymentAttempt>> GetPendingPaymentAttemptsAsync();
    Task<Payment> ReviewPaymentAttemptAsync(Guid attemptId, bool approve, string actor);
    Task<Payment> RecordGatewayPaymentAsync(PaymentWebhookRequest request);
    Task RevokePaymentLinkAsync(Guid paymentLinkId, string actor);
    Task<List<Expense>> GetExpensesAsync();
    Task SaveExpenseAsync(ExpenseForm form, string actor);
    Task DeleteExpenseAsync(Guid expenseId, string actor);
    Task<List<TenantDocument>> GetTenantDocumentsAsync(Guid? tenantId = null);
    Task SaveTenantDocumentAsync(TenantDocumentForm form, string actor);
    Task UpdateTenantDocumentStatusAsync(Guid documentId, string status, string actor);
    Task<List<MaintenanceTicket>> GetMaintenanceTicketsAsync(Guid? tenantId = null);
    Task SaveMaintenanceTicketAsync(MaintenanceTicketForm form, string actor);
    Task DeleteMaintenanceTicketAsync(Guid ticketId, string actor);
    Task<List<MessMenu>> GetMessMenusAsync(DateOnly? from = null, DateOnly? to = null);
    Task<List<MessAttendance>> GetMessAttendancesAsync(Guid tenantId, DateOnly? from = null, DateOnly? to = null);
    Task SaveMessMenuAsync(MessMenuForm form, string actor);
    Task DeleteMessMenuAsync(Guid menuId, string actor);
    Task SaveMessAttendanceAsync(MessAttendanceForm form, string actor);
    Task<Tenant?> GetTenantAsync(Guid tenantId);
    Task<Tenant?> GetTenantByEmailAsync(string email);
    Task<List<Bill>> GetTenantBillsAsync(Guid tenantId);
    Task<List<Payment>> GetTenantPaymentsAsync(Guid tenantId);
    Task<List<Enquiry>> GetEnquiriesAsync();
    Task CreateEnquiryAsync(ContactForm form);
    Task UpdateEnquiryStatusAsync(Guid enquiryId, string status, string actor);
    Task<List<GalleryImage>> GetGalleryAsync(bool publishedOnly = false);
    Task SaveGalleryImageAsync(GalleryForm form, string actor);
    Task DeleteGalleryImageAsync(Guid id, string actor);
    Task<List<Amenity>> GetAmenitiesAsync(bool publishedOnly = false);
    Task SaveAmenityAsync(AmenityForm form, string actor);
    Task DeleteAmenityAsync(Guid id, string actor);
    Task<List<Testimonial>> GetTestimonialsAsync(bool publishedOnly = false);
    Task SaveTestimonialAsync(TestimonialForm form, string actor);
    Task DeleteTestimonialAsync(Guid id, string actor);
    Task<List<AuditLog>> GetAuditLogsAsync();
    Task SaveSettingsAsync(HostelSetting setting, string actor);
}
